# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

beta_settings:
  cloud_sql_instances: sopra-fs26-group-43-server:europe-west6:sopraf-group43-postgre
