server.port=8080


# Password for the H2-Console
spring.datasource.url=jdbc:postgresql://34.65.97.254:5432/appdb
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect