server.port=8080


# Password for the H2-Console
spring.datasource.url=jdbc:postgresql:///appdb?cloudSqlInstance=sopra-fs26-group-43-server:europe-west6:sopraf-group43-postgre&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect